# Generated by Django 5.2.1 on 2025-05-08 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chatbot',
            new_name='Message',
        ),
    ]
